### ISSUE TITLE
Missing routing function for `17_4` Here map version; queries constrained to >= 2014-01-01

### ISSUE THREAD

**Issue by Nate-Wessel** [CityofToronto/bdit_tt_request_app#154]
For the earliest Here map version, `17_4`, we're missing the expected postgres function `here_gis.get_links_btwn_nodes_17_4`. Is this something that can be added? It would allow us to retrieve an extra two years of data between `'[2012-01-01,2014-01-01)'`. All the other map versions have this. 

@chmnata can this be added, please? And made accessible to `tt_request_bot`?

Thanks @AdK0101 for catching this!

By the way, I'm just realizing that the Here map versions do not actually start with the last two digits of the year they take effect...

**Comment by Nate-Wessel** [comment]
Once fixed, this query should no longer throw an error https://trans-bdit.intra.prod-toronto.ca/tt-request-backend/aggregate-travel-times/832469483/963185921/0/1/2013-04-01/2013-04-02/true/1234567

**Comment by chmnata** [comment]
We don't actually have data between '[2012-01-01,2014-01-01)' in our database at the moment, the oldest data we have is 2017-09

**Comment by Nate-Wessel** [comment]
Oohhh. Got it. 

Can we update `here.street_valid_range` to reflect that then?
