### ISSUE TITLE
Constrain spatial selectors to major intersections

### ISSUE THREAD

**Issue by Nate-Wessel** [CityofToronto/bdit_tt_request_app#16]
I.e. snap to nodes of the congestion network

I'm assuming we can still conflate the HERE nodes and CN nodes, just selecting from the subset of HERE nodes that are also CN nodes.

**Comment by tankedman** [comment]
"just selecting from the subset of HERE nodes that are also CN nodes." - Does this mean you would also like to crosscheck in the query to see if the current node is both a HERE node and a CN node?

**Comment by Nate-Wessel** [comment]
Maybe @chmnata can comment, but I thought that any congestion network node was also a HERE node by definition. No check necessary.

**Comment by Nate-Wessel** [comment]
@tankedman Natalie has confirmed this
