### ISSUE TITLE
Limit corridors to two nodes

### ISSUE THREAD

**Issue by Nate-Wessel** [CityofToronto/bdit_tt_request_app#38]
I don't think we want to be supporting routes complex enough to require three or more nodes. Corridors/segments should have only a start and end node. This can be enforced on the front-end and will reduce some complexity in the back-end.

**Comment by radumas** [comment]
I kind of forget how this works but wanted to point out that if we're using congestion network and only having 2 node corridors, I think the output should include travel time for each signal-signal segment. 

I would also caution a bit of a think/exploration on this. There might be instances with rather complicated intersections where one might need to force the corridor to route correctly by having an intermediate node. @chmnata do any examples come to mind?

**Comment by Nate-Wessel** [comment]
Something like this might not work with two points because we use _shortest-path_ routing.
![Screenshot 2023-04-19 at 11-09-51 OpenStreetMap](https://user-images.githubusercontent.com/7830465/233119913-fbd5af88-72e0-4425-a004-22718acb3a5c.png)

**Comment by Nate-Wessel** [comment]
Yep. No way around it; we need to support multi-node routes.
